version: '3.9'
services:
  postgres:
    container_name: voting_db
    image: postgres:16
    environment:
      - POSTGRES_DB=voting
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
    ports:
      - "5435:5432"
